import { PluginManifest } from '../../types/plugin';

export const LOCAL_PRESET_PLUGINS: PluginManifest[] = [
  {
    id: 'ai-gemini-pro',
    name: 'Gemini Pro & Flash AI Router',
    version: '1.2.0',
    author: 'AI Social Core Team',
    description: 'Dynamic model switching between Gemini 2.5 Flash and Gemini 2.5 Pro with prompt enhancement heuristics.',
    category: 'ai_provider',
    entryFile: 'index.js',
    icon: 'Bot',
    permissions: ['access_ai', 'read_storage', 'manage_settings'],
    dependencies: [],
    minAppVersion: '1.0.0',
    enabled: false,
    installedDate: '',
    updatedDate: '',
    checksum: 'a8f902bc4d1e',
    state: 'Detected',
  },
  {
    id: 'img-unsplash-pro',
    name: 'Unsplash & Media Engine',
    version: '1.0.4',
    author: 'Visual Studio Labs',
    description: 'High-resolution image search and contextual auto-tagging for social media banners and post attachments.',
    category: 'image_provider',
    entryFile: 'media.js',
    icon: 'Image',
    permissions: ['read_storage', 'write_storage', 'manage_settings'],
    dependencies: [],
    minAppVersion: '1.0.0',
    enabled: false,
    installedDate: '',
    updatedDate: '',
    checksum: 'b3e108fc990a',
    state: 'Detected',
  },
  {
    id: 'social-threads-connector',
    name: 'Meta Threads & X Connector',
    version: '2.0.1',
    author: 'Platform Sync Group',
    description: 'Native character limit verification, thread splitting, and cross-posting webhooks for Meta Threads.',
    category: 'social_platform',
    entryFile: 'connector.js',
    icon: 'Share2',
    permissions: ['access_publishing', 'read_storage', 'write_storage'],
    dependencies: [],
    minAppVersion: '1.0.0',
    enabled: false,
    installedDate: '',
    updatedDate: '',
    checksum: 'c4d817ef882b',
    state: 'Detected',
  },
  {
    id: 'workflow-scheduler-plus',
    name: 'Optimal Time Scheduler',
    version: '1.1.0',
    author: 'Automation Guild',
    description: 'Calculates historical peak engagement hours and automatically assigns post publishing queues.',
    category: 'workflow',
    entryFile: 'workflow.js',
    icon: 'Workflow',
    permissions: ['access_workflow', 'read_analytics', 'write_storage'],
    dependencies: [],
    minAppVersion: '1.0.0',
    enabled: false,
    installedDate: '',
    updatedDate: '',
    checksum: 'd9e0321a44c2',
    state: 'Detected',
  },
  {
    id: 'analytics-heatmaps',
    name: 'Engagement Heatmap Visualizer',
    version: '1.0.0',
    author: 'DataVis Ops',
    description: 'Renders weekly audience activity heatmaps and platform conversion performance charts.',
    category: 'analytics',
    entryFile: 'analytics.js',
    icon: 'BarChart3',
    permissions: ['read_analytics', 'read_storage'],
    dependencies: [],
    minAppVersion: '1.0.0',
    enabled: false,
    installedDate: '',
    updatedDate: '',
    checksum: 'e712398a11bc',
    state: 'Detected',
  },
  {
    id: 'export-markdown-json',
    name: 'Multi-Format Export Suite',
    version: '1.3.0',
    author: 'Content Exporters',
    description: 'Export drafts, published logs, and scheduled calendars to Markdown, JSON, and CSV packages.',
    category: 'export',
    entryFile: 'exporter.js',
    icon: 'Download',
    permissions: ['read_storage'],
    dependencies: [],
    minAppVersion: '1.0.0',
    enabled: false,
    installedDate: '',
    updatedDate: '',
    checksum: 'f102938d44ee',
    state: 'Detected',
  },
  {
    id: 'import-csv-notion',
    name: 'Notion & CSV Content Importer',
    version: '1.0.2',
    author: 'Content Migration Tools',
    description: 'Bulk import post ideas, hashtags, and editorial calendars directly into local IndexedDB queues.',
    category: 'import',
    entryFile: 'importer.js',
    icon: 'Upload',
    permissions: ['write_storage', 'read_storage'],
    dependencies: [],
    minAppVersion: '1.0.0',
    enabled: false,
    installedDate: '',
    updatedDate: '',
    checksum: '11aa88bc9901',
    state: 'Detected',
  },
  {
    id: 'backup-auto-snapshot',
    name: 'Automated Snapshot Guard',
    version: '1.4.1',
    author: 'Data Protection Lab',
    description: 'Schedules background IndexedDB state snapshots with automatic version checksum validation.',
    category: 'backup',
    entryFile: 'backup.js',
    icon: 'Database',
    permissions: ['read_storage', 'write_storage', 'manage_settings'],
    dependencies: [],
    minAppVersion: '1.0.0',
    enabled: false,
    installedDate: '',
    updatedDate: '',
    checksum: '22bb77cc8812',
    state: 'Detected',
  },
  {
    id: 'storage-indexeddb-cleaner',
    name: 'Storage Compression Engine',
    version: '1.0.1',
    author: 'Storage Ops',
    description: 'Compresses stale activity logs and purges expired draft media cache to save IndexedDB space.',
    category: 'storage',
    entryFile: 'storage.js',
    icon: 'HardDrive',
    permissions: ['read_storage', 'write_storage'],
    dependencies: [],
    minAppVersion: '1.0.0',
    enabled: false,
    installedDate: '',
    updatedDate: '',
    checksum: '33cc66dd7723',
    state: 'Detected',
  },
  {
    id: 'theme-midnight-synth',
    name: 'Midnight Synth Theme Pack',
    version: '1.0.0',
    author: 'UI Atelier',
    description: 'Custom dark slate palette with neon indigo accents and high-contrast typography controls.',
    category: 'theme',
    entryFile: 'theme.js',
    icon: 'Palette',
    permissions: ['write_storage', 'manage_settings'],
    dependencies: [],
    minAppVersion: '1.0.0',
    enabled: false,
    installedDate: '',
    updatedDate: '',
    checksum: '44dd55ee6634',
    state: 'Detected',
  },
  {
    id: 'notification-desktop-webhook',
    name: 'Dashboard Alert Engine',
    version: '1.1.2',
    author: 'Alert Systems',
    description: 'Customizable toast alerts for scheduled post execution, workflow triggers, and storage limits.',
    category: 'notification',
    entryFile: 'notifier.js',
    icon: 'Bell',
    permissions: ['send_notification', 'read_storage'],
    dependencies: [],
    minAppVersion: '1.0.0',
    enabled: false,
    installedDate: '',
    updatedDate: '',
    checksum: '55ee44ff5545',
    state: 'Detected',
  },
  {
    id: 'webhook-slack-discord',
    name: 'Slack & Discord Webhook Relay',
    version: '1.2.0',
    author: 'Integration Relay',
    description: 'Dispatches real-time webhooks whenever posts are published, approved, or flagged for revision.',
    category: 'webhook',
    entryFile: 'webhook.js',
    icon: 'Webhook',
    permissions: ['send_notification', 'read_storage', 'access_publishing'],
    dependencies: [],
    minAppVersion: '1.0.0',
    enabled: false,
    installedDate: '',
    updatedDate: '',
    checksum: '66ff33aa4456',
    state: 'Detected',
  },
];
